# -*- coding: utf-8 -*-
"""EDA_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLIKQfpN0KKfth-DZOqxaD9gTOgnkbG8
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

df = pd.read_csv('bad-drivers.csv')
df.columns = ['state', 'fatal_collisions_rate', 'speeding_percent', 'alcohol_percent', 'not_distracted_percent', 'no_prior_accidents' ,'insurance_premium' , 'insurance_losses']
df.head()

df.tail()

df.info()

df.describe()

"""**Univariate Analysis**:"""

sns.histplot(data=df, x='fatal_collisions_rate', bins=10)

sns.displot(data=df, x='no_prior_accidents')

plt.figure(figsize=(15,20))
plt.pie(df['fatal_collisions_rate'] , labels = df['state'], autopct="%1.2f%%") ;

"""**Bivariate Analysis**"""

df.head(1)

plt.figure(figsize=(15,10))
sns.barplot(data=df, x='speeding_percent', y='alcohol_percent');
plt.yticks(range(16, 44, 3))
plt.show();

sns.scatterplot(data=df, x='speeding_percent', y='alcohol_percent');

sns.scatterplot(data=df, x='speeding_percent', y='insurance_losses')

plt.figure(figsize=(20,10))
sns.barplot(data=df, x='speeding_percent', y='insurance_losses')
plt.show()

"""**Multivariate Analysis**"""

sns.pairplot(data=df, vars=['fatal_collisions_rate', 'speeding_percent', 'alcohol_percent',])

plt.figure(figsize=(10,8))
sns.heatmap(df[['fatal_collisions_rate', 'speeding_percent', 'alcohol_percent']].corr(), annot=True, cmap='coolwarm')

plt.figure(figsize=(11,10))
sns.scatterplot(data=df, x='fatal_collisions_rate', y='speeding_percent', hue='alcohol_percent');
